%  Superb recovery for yaleb10, 10% noise, scaled twice
% [Uc, Ur, T, E] = brpca_mmx(X, 40, 'maxiter', 1000, ...
%      'lambda', 0.00002, ...
% ...,%     'mu', 1e-4, ...
%     'alpha_c', 1, 'alpha_r', 1, 'rho', 1.05);

% YaleB*10 with 60% noise - choose r = 40 for really good
% [Uc, Ur, T, E] = brpca(X, 50, 'maxiter', 1000, ...
%     'lambda', 1e-3, ...
% ...,%     'mu', 1e-4, ...
%     'alpha_c', 1, 'alpha_r', 1, 'rho', 1.1, 'mean', 0, 'ground_o', O, 'mmx', 1);

% YaleB*10 with 60% noise - lambda = 5.5e-2 is really good for 10 and 30%
% 60% noise on 1st person: take lambda = 7e-2 and rho = 1.2 and alpha_t = 1e-1
[Uc, Ur, T, E] = rpca2d(X, 20, 'maxiter', 1000, ...
...%    'lambda', 1.5e-3, ...
    'lambda', 7e-2, ...
    'ground_O', O, ...
    'alpha_c', 1, 'alpha_r', 1, 'alpha_t', 1e-1, 'rho', 1.2, ...
    'mean', 0, 'mmx', 1, ...
    'parallel', 0, 'time', 0);


% [Uc, Ur, T, E] = brpca_mmx(X, 30, 'maxiter', 1000, 'rho', 2.1);
% max_rec_e(E, E_ori)
max_rec_o(Uc,T,Ur,O)
max_rec_f(Uc,T,Ur,E,X)

show4(1,X,O,Uc,Ur,T,E)
norm(O(:,:,1) - Uc*T(:,:,1)*Ur', 'fro') / norm(O(:,:,1), 'fro')
norm(O(:,:,11) - Uc*T(:,:,11)*Ur', 'fro') / norm(O(:,:,11), 'fro')
norm(O(:,:,21) - Uc*T(:,:,21)*Ur', 'fro') / norm(O(:,:,21), 'fro')

E(:,:,1);